name: "Tests"

on:
  pull_request:
  push:

jobs:
  phpunit:
    name: PHPUnit Tests
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        php:
          - "7.4"
          - "8.0"
          - "8.1"
        dependency-versions:
          - "highest"
        include:
          - php: "7.4"
            dependency-versions: "lowest"
          - php: "8.2"
            composer-options: "--ignore-platform-reqs"

    steps:
        - uses: actions/checkout@v2
          with:
            fetch-depth: 2

        - name: Setup PHP
          uses: shivammathur/setup-php@v2
          with:
            php-version: ${{ matrix.php }}

        - name: Install Dependencies
          uses: "ramsey/composer-install@v2"
          with:
            dependency-versions: "${{ matrix.dependency-versions }}"
            composer-options: "${{ matrix.composer-options }}"

        - name: Run PHPUnit
          run: "vendor/bin/phpunit --coverage-clover=coverage.clover"

        - name: Upload Coverage
          if: github.repository_owner == 'jmikola'
          run: "vendor/bin/ocular code-coverage:upload --format=php-clover coverage.clover"
